/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog': RouteRecordInfo<
      '/blog',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/posts/2025-11-28-blog-quote': RouteRecordInfo<
      '/posts/2025-11-28-blog-quote',
      '/posts/2025-11-28-blog-quote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025-11-28-coursework-cs-test-6': RouteRecordInfo<
      '/posts/2025-11-28-coursework-cs-test-6',
      '/posts/2025-11-28-coursework-cs-test-6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025-12-02-note-dl-1': RouteRecordInfo<
      '/posts/2025-12-02-note-dl-1',
      '/posts/2025-12-02-note-dl-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2025-12-12-note-dl-2': RouteRecordInfo<
      '/posts/2025-12-12-note-dl-2',
      '/posts/2025-12-12-note-dl-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-01-22-blog-imgdeno-cnn': RouteRecordInfo<
      '/posts/2026-01-22-blog-imgdeno-cnn',
      '/posts/2026-01-22-blog-imgdeno-cnn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-03-07-note-dl-3': RouteRecordInfo<
      '/posts/2026-03-07-note-dl-3',
      '/posts/2026-03-07-note-dl-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-03-31-note-move-constructor': RouteRecordInfo<
      '/posts/2026-03-31-note-move-constructor',
      '/posts/2026-03-31-note-move-constructor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-04-08-blog-unitree-go2-devlog-1': RouteRecordInfo<
      '/posts/2026-04-08-blog-unitree-go2-devlog-1',
      '/posts/2026-04-08-blog-unitree-go2-devlog-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-04-23-blog-ascendc-certivicate': RouteRecordInfo<
      '/posts/2026-04-23-blog-ascendc-certivicate',
      '/posts/2026-04-23-blog-ascendc-certivicate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026-04-29-blog-opi-ai-studio-windows': RouteRecordInfo<
      '/posts/2026-04-29-blog-opi-ai-studio-windows',
      '/posts/2026-04-29-blog-opi-ai-studio-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/README': RouteRecordInfo<
      '/README',
      '/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/about.md': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/blog.vue': {
      routes:
        | '/blog'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/posts/2025-11-28-blog-quote.md': {
      routes:
        | '/posts/2025-11-28-blog-quote'
      views:
        | never
    }
    'src/pages/posts/2025-11-28-coursework-cs-test-6.md': {
      routes:
        | '/posts/2025-11-28-coursework-cs-test-6'
      views:
        | never
    }
    'src/pages/posts/2025-12-02-note-dl-1.md': {
      routes:
        | '/posts/2025-12-02-note-dl-1'
      views:
        | never
    }
    'src/pages/posts/2025-12-12-note-dl-2.md': {
      routes:
        | '/posts/2025-12-12-note-dl-2'
      views:
        | never
    }
    'src/pages/posts/2026-01-22-blog-imgdeno-cnn.md': {
      routes:
        | '/posts/2026-01-22-blog-imgdeno-cnn'
      views:
        | never
    }
    'src/pages/posts/2026-03-07-note-dl-3.md': {
      routes:
        | '/posts/2026-03-07-note-dl-3'
      views:
        | never
    }
    'src/pages/posts/2026-03-31-note-move-constructor.md': {
      routes:
        | '/posts/2026-03-31-note-move-constructor'
      views:
        | never
    }
    'src/pages/posts/2026-04-08-blog-unitree-go2-devlog-1.md': {
      routes:
        | '/posts/2026-04-08-blog-unitree-go2-devlog-1'
      views:
        | never
    }
    'src/pages/posts/2026-04-23-blog-ascendc-certivicate.md': {
      routes:
        | '/posts/2026-04-23-blog-ascendc-certivicate'
      views:
        | never
    }
    'src/pages/posts/2026-04-29-blog-opi-ai-studio-windows.md': {
      routes:
        | '/posts/2026-04-29-blog-opi-ai-studio-windows'
      views:
        | never
    }
    'src/pages/README.md': {
      routes:
        | '/README'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
